export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
  COHABITING = 'COHABITING',
}

export enum SpiritualLevel {
  GUEST = 'GUEST',
  PRE_RETREAT = 'PRE_RETREAT',
  RETREAT = 'RETREAT',
  POST_RETREAT = 'POST_RETREAT',
  LEADERSHIP_SCHOOL_1 = 'LEADERSHIP_SCHOOL_1',
  LEADERSHIP_SCHOOL_2 = 'LEADERSHIP_SCHOOL_2',
  LEADERSHIP_SCHOOL_3 = 'LEADERSHIP_SCHOOL_3',
  LEADERSHIP_SCHOOL_4 = 'LEADERSHIP_SCHOOL_4',
  LEADERSHIP_SCHOOL_5 = 'LEADERSHIP_SCHOOL_5',
  LEADERSHIP_SCHOOL_6 = 'LEADERSHIP_SCHOOL_6',
  LEADER = 'LEADER',
  CELL_LEADER = 'CELL_LEADER',
  LEADERSHIP_SCHOOL_TEACHER = 'LEADERSHIP_SCHOOL_TEACHER',
}